on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      #SETUP KEY
      - run: set -eu
      - run: mkdir "/home/runner/.shh/"
      - run: echo "${{secrets.SSH_PRIVATE_KEY}}" > "/home/runner/.shh/deploy_key"
      - run: chmod 600 "/home/runner/.shh/deploy_key"

      #Deploy and install
      - name: Deploy and install
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          # if ssh port differs of usual 22
          # port: ${{ secrets.SSH_PORT  }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/deploy/emgtestwork && npm i && npm run client:install && npm run client:build && pm2 restart emgtestwork
