name: Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      #SETUP KEY
      - run: set -eu
      - run: mkdir "/home/runner/.shh/"
      - run: echo "${{secrets.SSH_PRIVATE_KEY}}" > "/home/runner/.shh/key"
      - run: chmod 600 "/home/runner/.shh/key"

      BUILD
      - run: npm install
      - run: npm run client:install
      - run: npm run client:build
      #DEPLOY
      - run: rsync -e "ssh -i /home/runner/.shh/key -o StrictHostKeyChecking=no" --archive --compress --delete . ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:/home/vitossvx/deploy/emgtestwork
